version: '3'

services:
  bitcoin-testnet:
    image: ruimarinho/bitcoin-core:0.16.3
    ports:
      - "18332:18332"
    command:
      -printtoconsole
      -server
      -testnet=1
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
